# Generated by Django 4.2.1 on 2023-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='URL Amigable')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el :')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Actualizado el :')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
    ]
